# fly.toml app configuration file generated for gem-coop-beta on 2026-01-10T07:35:34-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gem-coop-staging'
primary_region = 'ord'

[deploy]
release_command = 'bin/rails db:prepare'

[build]

[env]
WEB_CONCURRENCY = 'auto' # one process per CPU core
RAILS_MAX_THREADS = "15"

[processes]
app = 'bin/rails server'
worker = 'bin/sidekiq'

[http_service]
processes = ['app']
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
max_machines_running = 2

[[http_service.checks]]
interval = '10s'
timeout = '2s'
grace_period = '5s'
method = 'GET'
path = '/up'
protocol = 'http'
tls_skip_verify = false

[http_service.checks.headers]
X-Forwarded-Proto = 'https'

[[vm]]
cpu_kind = 'performance'
cpus = 1
memory = '2048mb'

[[statics]]
guest_path = '/rails/public'
url_prefix = '/'
