---
:queues:
  - mailer
  - critical
  - default
  - low
  - mirror
:scheduler:
  :schedule:
    MirrorImportJob:
      cron: "* * * * *"
    CooldownUpdateJob:
      cron: "5 4 * * *"
    CompactMirrorIndexesJob:
      cron: "41 4 2 * *"
    ClearExpiredPushKeysJob:
      cron: "6 * * * *"
