test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# We use Fastly's S3-compatible Object Storage
# https://docs.fastly.com/products/object-storage
fastly:
  service: S3
  endpoint: '<%= ENV["AWS_ENDPOINT_URL_S3"] %>'
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
  bucket: <%= ENV["BUCKET_NAME"] %>
  force_path_style: true # this is required for Fastly Object Storage
