name: "Deploy to fly.io"
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types: ["completed"]
    branches: ["main"]
permissions:
  contents: read
  deployments: write
jobs:
  deploy-staging:
    name: Deploy staging
    environment: Staging
    if: ${{ github.repository == 'gem-coop/peak' }}
    runs-on: ubuntu-latest
    concurrency:
      group: staging-deploy
      cancel-in-progress: false
    steps:
      - id: deployment
        uses: bobheadxi/deployments@v1.5.0
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Staging
      - uses: actions/checkout@v7
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: fly deploy -a gem-coop-staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy -a gem-coop-staging --remote-only \
          -e BUILT_BY=github-actions \
          -e GIT_SHA=$GITHUB_SHA \
          -e BUNDLE_WITH=avo \
          --build-secret BUNDLE_PACKAGER__DEV=${{ secrets.BUNDLE_PACKAGER__DEV }}
      - uses: bobheadxi/deployments@v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: Staging
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          override: false
          auto_inactive: true
      - uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}
          environment: staging
  deploy-production:
    name: Deploy production
    needs: [deploy-staging]
    environment: Production
    if: ${{ github.repository == 'gem-coop/peak' }}
    runs-on: ubuntu-latest
    concurrency:
      group: production-deploy
      cancel-in-progress: false
    steps:
      - id: deployment
        uses: bobheadxi/deployments@v1.5.0
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Production
      - uses: actions/checkout@v7
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: fly deploy -a gem-coop
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy -a gem-coop --remote-only \
          -e BUILT_BY=github-actions \
          -e GIT_SHA=$GITHUB_SHA \
          -e BUNDLE_WITH=avo \
          --build-secret BUNDLE_PACKAGER__DEV=${{ secrets.BUNDLE_PACKAGER__DEV }}
      - uses: bobheadxi/deployments@v1.5.0
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: Production
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          override: false
          auto_inactive: true
      - uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}
          environment: production
